# Generated by Django 4.2.4 on 2023-08-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Desk', '0002_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='is_closed',
        ),
    ]
